server:
  port: 3000
  address: localhost

spring:
  application:
    name: apirest

  datasource:
    url: jdbc:postgresql://localhost:5432/db_punto
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

afip:
  enabled: true
  homologacion: false
  cuit: "27242400068"
  pto-vta: 3
  cbte-tipo: 6
  token-xml-path: classpath:certificados/TA.xml
  auto-facturar-en-venta: true
  validar-token-en-login: true
  php-script-path: "C:/Users/santi/OneDrive/Documentos/NetBeansProjects/ATHLAND/ARCHIVOS AFIP VEIJOS/certificados/wsaa-client.php"
  php-script-path-homologacion: "C:/Users/santi/OneDrive/Documentos/NetBeansProjects/ATHLAND/testing/wsaa-client.php"
  empresa:
    razon-social: "ATHLAND S.R.L."
    direccion: ""
    cuit: "27242400068"
    condicion-iva: "IVA Responsable Inscripto"
    iibb: ""
    inicio-actividad: ""