server:
  port: ${PORT:3000}
  address: 0.0.0.0

spring:
  application:
    name: apirest

  main:
    banner-mode: off

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-noisy-wildflower-acnenufm-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_KszX8HyOTk4B&sslmode=require&channelBinding=require}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

logging:
  level:
    root: WARN
    com.vida.apirest: INFO
    com.vida.apirest.controller.DashboardController: INFO
    com.vida.apirest.servicies.DashboardService: INFO
    com.vida.apirest.servicies.CreditoCuentaService: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

afip:
  enabled: true
  homologacion: false
  cuit: "27242400068"
  pto-vta: 3
  cbte-tipo: 6
  token-xml-path: classpath:certificados/TA.xml
  auto-facturar-en-venta: true
  validar-token-en-login: true
  php-script-path: "C:/Users/santi/OneDrive/Documentos/NetBeansProjects/ATHLAND/ARCHIVOS AFIP VEIJOS/certificados/wsaa-client.php"
  php-script-path-homologacion: "C:/Users/santi/OneDrive/Documentos/NetBeansProjects/ATHLAND/testing/wsaa-client.php"
  empresa:
    razon-social: "ATHLAND S.R.L."
    direccion: ""
    cuit: "27242400068"
    condicion-iva: "IVA Responsable Inscripto"
    iibb: ""
    inicio-actividad: ""